### PR TITLE
Check if user can create a view. Fixes #616

### LINKED ISSUE #616: Check that MySQL user has permission to create views
The `structure_unified` view cannot be created at import time if the MySQL user does not have permission to create a view. We don't catch this error, so the site just mysteriously fails to work after an apparently-successful import. Make this part of the sanity-checking that we do prior to importing.

### PR DESCRIPTION
**Pull request by krues8dr**

### CODE REVIEW

**Comment by waldoj** [comment]
Well, that's a Pythonic way to check this. :)

**Comment by krues8dr** [comment]
You had something else in mind?  I've been writing a lot of Python lately. :man_shrugging:

**Comment by krues8dr** [comment]
I'm definitely not going to go around scraping MySQL's insane grant syntax, that's for sure...

http://dev.mysql.com/doc/refman/5.7/en/show-grants.html

**Comment by waldoj** [comment]
I tend to compartmentalize—I think Pythonically when writing Python, but not PHP. But it's the right approach here!

**Pull request merged**
