### PR TITLE
Combine h1 and h2 headers on the law page

### LINKED ISSUE #599: Reconsider semantic markup of catch lines
Right now, we put the section identifier in an H1, and the catch line in an H2, e.g.:

```
<h1>§ 18.2-250</h1>
<h2>Possession of controlled substances unlawful.</h2>
```

This is logical, but the effect of it is that Google thinks that the page title is `§ 18.2-250` (or, rather, `18.2-250`, for reasons that only Google knows), and that's a substantially less useful thing for somebody to see in search results than `Possession of controlled substances unlawful`. It seems to me that how we do it is "right," but that it's leading to a wrong outcome.

### PR DESCRIPTION
**Pull request by waldoj**
Closes #599.

### CODE REVIEW

**Comment by waldoj** [comment]
We were using `$content->append()` to add an `<h2>` to the law page, and now we're using it to add a `<span>`. instead. So what's the need for a template change?

**Comment by krues8dr** [comment]
I see an <h1> being removed here, and replaced with a span: ce10b828307f4ff9095556bb8efd7ea930558ed6

Am I reading this wrong?

**Comment by waldoj** [comment]
Yeah—that was actually a bug. It was producing `<h1><h1>` in the code. :)

**Comment by krues8dr** [comment]
Ahhhhhhh nice.

**Comment by krues8dr** [comment]
:+1:

**Pull request merged**
